### ISSUE TITLE
Mojolicious::Controller::render_not_found is DEPRECATED

### ISSUE THREAD

**Issue by eserte** [plicease/Yars#13]
See http://www.cpantesters.org/cpan/report/51ca89d6-a7e6-11e4-a9a5-11d7dfbfc7aa for a sample test report with a lot of lines saying that Mojolicious::Controller::render_not_found is deprecated.

**Comment by plicease** [comment]
1.06 should fix this.  It is identical except that it requires a newer version of Clustericious which is where this bug is, and where it was already fixed.

If you see this again in 1.06, please let me know.
