### ISSUE TITLE
Yars client route 'content'

### ISSUE THREAD

**Issue by CurtTilmes** [plicease/Yars#15]
yarsclient has a 'content route':

    route_doc content  => "<filename> <md5>";

but it doesn't appear to be implemented.

(I thought it might be something like a "cat" to send content to STDOUT instead of into a file?)

**Comment by CurtTilmes** [comment]
yarsclient get <md5> <filename> 

is send content to STDOUT, so it probably isn't that.

**Comment by plicease** [comment]
Looks like it was renamed without updating the route_doc:

https://github.com/plicease/Yars-Client/commit/7256a4553fd60f51a7bffe2b0ae3920c82a492ff
https://github.com/plicease/Yars-Client/commit/9f8890db064c7aba4ae3846947d95c83b55173ff

**Comment by plicease** [comment]
I'm removing the documentation for the old content route.  I'm not against implementing it for compatibility, but nobody has been asking for it.
