### ISSUE TITLE
Set HTTP Server header to Yars something with version

### ISSUE THREAD

**Issue by CurtTilmes** [plicease/Yars#21]
Right now it just defaults to Mojolicious (Perl).

Might be able to set it in Clustericious so every Clustericious App sets it.

**Comment by plicease** [comment]
I agree this is a sensical thing.

**Comment by plicease** [comment]
This will be included with Clustericious 1.01

https://github.com/plicease/Clustericious/commit/3cda79d0878a79b7a59b1d671575dd12283f5385
